steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rigger-platform-api:$BUILD_ID', '.']
  
  # Deploy directly to Cloud Run without pushing to registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'rigger-platform-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/rigger-platform-api:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'